# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal.proto

require 'google/protobuf'

require_relative 'utils_pb'
require_relative 'timeline_pb'
require_relative 'google/protobuf/wrappers_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "eva.Internal" do
    optional :type, :enum, 1, "eva.Internal.InternalType"
    oneof :content do
      optional :setpoints, :message, 2, "eva.Setpoints"
      optional :payload, :message, 3, "eva.Upload"
      optional :torques, :message, 4, "eva.Torques"
      optional :bd_state, :message, 5, "eva.BDState"
      optional :torque_telemetry, :message, 6, "eva.TorqueTelemetry"
      optional :upload_packet, :message, 7, "eva.UploadPacket"
    end
  end
  add_enum "eva.Internal.InternalType" do
    value :RESET_MEMORY, 0
    value :LOAD_SETPOINTS, 1
    value :RUN, 2
    value :BRANCH_DONE, 3
    value :RESET_ERRORS, 4
    value :REFRESH_DATA, 5
    value :UPLOAD, 6
    value :LOAD_TORQUES, 7
    value :REQUEST_BD, 8
    value :START_BD, 9
    value :STOP_BD, 10
    value :BD_STATE, 11
    value :BD_STOPPED, 12
    value :TORQUE_TELEMETRY, 13
    value :TOOLPATH_DONE, 14
  end
  add_message "eva.UploadPacket" do
    optional :servo_id, :message, 1, "google.protobuf.UInt32Value"
    repeated :payload, :message, 2, "eva.Upload"
  end
  add_message "eva.Setpoints" do
    optional :s0, :message, 1, "eva.Setpoint"
    optional :s1, :message, 2, "eva.Setpoint"
    optional :s2, :message, 3, "eva.Setpoint"
    optional :s3, :message, 4, "eva.Setpoint"
    optional :s4, :message, 5, "eva.Setpoint"
    optional :s5, :message, 6, "eva.Setpoint"
    optional :s6, :message, 7, "eva.Setpoint"
  end
  add_message "eva.Setpoint" do
    optional :angle, :float, 1
    optional :velocity, :float, 2
  end
  add_message "eva.Upload" do
    optional :input, :float, 1
    optional :output, :float, 2
    optional :motor_command, :sint32, 3
    optional :current, :uint32, 4
    optional :wp, :uint32, 5
  end
  add_message "eva.TorqueTelemetry" do
    optional :angle, :float, 1
    optional :velocity, :float, 2
    optional :current, :uint32, 3
  end
  add_message "eva.Torques" do
    optional :tau0, :float, 1
    optional :tau1, :float, 2
    optional :tau2, :float, 3
    optional :tau3, :float, 4
    optional :tau4, :float, 5
    optional :tau5, :float, 6
    optional :tau6, :float, 7
  end
  add_message "eva.BDState" do
    optional :enabled, :bool, 1
  end
  add_message "eva.SDO" do
    optional :index, :uint32, 1
    optional :sub_index, :uint32, 2
    optional :length, :uint32, 3
    optional :data, :uint32, 4
    optional :rw, :enum, 5, "eva.SDO.ReadWrite"
    optional :servo, :uint32, 6
  end
  add_enum "eva.SDO.ReadWrite" do
    value :SDO_RESULT, 0
    value :SDO_READ, 1
    value :SDO_WRITE, 2
  end
  add_message "eva.Settings" do
    optional :home, :message, 1, "eva.Angles"
    optional :timeline, :message, 2, "eva.Timeline"
  end
end

module Eva
  Internal = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.Internal").msgclass
  Internal::InternalType = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.Internal.InternalType").enummodule
  UploadPacket = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.UploadPacket").msgclass
  Setpoints = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.Setpoints").msgclass
  Setpoint = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.Setpoint").msgclass
  Upload = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.Upload").msgclass
  TorqueTelemetry = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.TorqueTelemetry").msgclass
  Torques = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.Torques").msgclass
  BDState = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.BDState").msgclass
  SDO = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.SDO").msgclass
  SDO::ReadWrite = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.SDO.ReadWrite").enummodule
  Settings = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.Settings").msgclass
end
