# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timeline.proto

require 'google/protobuf'

require_relative 'utils_pb'
require_relative 'google/protobuf/wrappers_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "eva.Timeline" do
    repeated :objects, :message, 1, "eva.TimelineObject"
    optional :speed, :float, 2
    optional :name, :string, 3
  end
  add_message "eva.TimelineObject" do
    optional :type, :enum, 1, "eva.TimelineObject.TimelineObjectType"
    oneof :timeline_objects do
      optional :waypoint, :message, 2, "eva.Waypoint"
      optional :conditional, :message, 3, "eva.Conditional"
      optional :output, :message, 4, "eva.Output"
      optional :wait, :message, 5, "eva.Wait"
      optional :grid, :message, 6, "eva.Grid"
      optional :grid_waypoint, :message, 7, "eva.GridWaypoint"
    end
  end
  add_enum "eva.TimelineObject.TimelineObjectType" do
    value :WAYPOINT, 0
    value :CONDITIONAL, 1
    value :RESTART, 2
    value :OUTPUT, 3
    value :WAIT, 4
    value :GRID, 5
    value :GRID_WAYPOINT, 6
  end
  add_message "eva.Waypoint" do
    optional :type, :enum, 1, "eva.Waypoint.WaypointType"
    optional :time, :float, 2
    optional :interpolation_weight, :float, 3
    optional :a0, :float, 4
    optional :a1, :float, 5
    optional :a2, :float, 6
    optional :a3, :float, 7
    optional :a4, :float, 8
    optional :a5, :float, 9
    optional :a6, :float, 10
  end
  add_enum "eva.Waypoint.WaypointType" do
    value :LINEAR, 0
    value :INTERPOLATION, 1
  end
  add_message "eva.Wait" do
    optional :type, :enum, 1, "eva.Wait.WaitType"
    oneof :wait_types do
      optional :time, :int32, 2
      optional :test, :message, 3, "eva.Test"
    end
  end
  add_enum "eva.Wait.WaitType" do
    value :TIME, 0
    value :TEST, 1
  end
  add_message "eva.Conditional" do
    repeated :branches, :message, 1, "eva.Branch"
  end
  add_message "eva.Branch" do
    optional :test, :message, 1, "eva.Test"
    repeated :timeline, :message, 2, "eva.TimelineObject"
  end
  add_message "eva.Test" do
    optional :channel, :message, 1, "eva.Channel"
    optional :direction, :enum, 2, "eva.Test.TestDirection"
    optional :mode, :enum, 3, "eva.Test.TestModes"
    oneof :values do
      optional :digital_value, :bool, 4
      optional :analog_value, :float, 5
      optional :threshold_value, :message, 6, "eva.TestThreshold"
    end
  end
  add_enum "eva.Test.TestDirection" do
    value :INPUT, 0
    value :OUTPUT, 1
  end
  add_enum "eva.Test.TestModes" do
    value :DIGITAL, 0
    value :DIRECT, 1
    value :THRESHOLD, 2
  end
  add_message "eva.TestThreshold" do
    optional :type, :enum, 1, "eva.TestThreshold.TestThresholdType"
    optional :threshold_upper, :float, 2
    optional :threshold_lower, :float, 3
  end
  add_enum "eva.TestThreshold.TestThresholdType" do
    value :INSIDE, 0
    value :OUTSIDE, 1
    value :ABOVE, 2
    value :BELOW, 3
  end
  add_message "eva.Output" do
    optional :channel, :message, 1, "eva.Channel"
    oneof :value do
      optional :analog_value, :float, 2
      optional :digital_value, :bool, 3
    end
  end
  add_message "eva.Channel" do
    optional :type, :enum, 1, "eva.Channel.ChannelType"
    optional :number, :uint32, 2
  end
  add_enum "eva.Channel.ChannelType" do
    value :DIGITAL, 0
    value :ANALOG, 1
  end
  add_message "eva.Grid" do
    optional :cols, :uint32, 1
    optional :rows, :uint32, 2
    optional :waypoint_0, :message, 3, "eva.Angles"
    optional :waypoint_x, :message, 4, "eva.Angles"
    optional :waypoint_y, :message, 5, "eva.Angles"
    repeated :timeline, :message, 6, "eva.TimelineObject"
  end
  add_message "eva.GridWaypoint" do
    optional :time, :float, 1
    optional :z_offset, :message, 2, "google.protobuf.FloatValue"
  end
end

module Eva
  Timeline = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.Timeline").msgclass
  TimelineObject = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.TimelineObject").msgclass
  TimelineObject::TimelineObjectType = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.TimelineObject.TimelineObjectType").enummodule
  Waypoint = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.Waypoint").msgclass
  Waypoint::WaypointType = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.Waypoint.WaypointType").enummodule
  Wait = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.Wait").msgclass
  Wait::WaitType = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.Wait.WaitType").enummodule
  Conditional = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.Conditional").msgclass
  Branch = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.Branch").msgclass
  Test = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.Test").msgclass
  Test::TestDirection = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.Test.TestDirection").enummodule
  Test::TestModes = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.Test.TestModes").enummodule
  TestThreshold = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.TestThreshold").msgclass
  TestThreshold::TestThresholdType = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.TestThreshold.TestThresholdType").enummodule
  Output = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.Output").msgclass
  Channel = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.Channel").msgclass
  Channel::ChannelType = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.Channel.ChannelType").enummodule
  Grid = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.Grid").msgclass
  GridWaypoint = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.GridWaypoint").msgclass
end
