# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "eva.Angles" do
    optional :a0, :float, 1
    optional :a1, :float, 2
    optional :a2, :float, 3
    optional :a3, :float, 4
    optional :a4, :float, 5
    optional :a5, :float, 6
    optional :a6, :float, 7
  end
end

module Eva
  Angles = Google::Protobuf::DescriptorPool.generated_pool.lookup("eva.Angles").msgclass
end
